[env:mhetesp32devkit]
platform = espressif32
board = mhetesp32devkit
framework = arduino
monitor_speed = 9600
monitor_filters = esp32_exception_decoder

lib_deps =
  madhephaestus/ESP32Servo
  marcoschwartz/LiquidCrystal_I2C
